### PR TITLE
Flyway/classpath support

### LINKED ISSUE #133: Flyway Resource Loading is not working
**Describe the bug**
Flyway cannot locate resources on its classpath

**To Reproduce**
1. Create a Spring Boot `war` plugin
2. Bundle Flyway
3. Add a resource to classpath root: `v00000.0001.sql`
4. Instantiate flyway as follows: 
```  return Flyway.configure()
    .table("schema_version")
    .dataSource(dataSource)
    .sqlMigrationPrefix("v")
    .ignoreMissingMigrations(true)
    .cleanDisabled(true)
    .outOfOrder(true)

    .locations("classpath:/flyway")
    .load();
    ```

**Expected behavior**
Flyway migration should be located

### PR DESCRIPTION
**Pull request by josiahhaswell**
1. Fixed an issue with exporting resources to the local module (fixes #133)
2. Added example for using Flyway custom LoadableResource

### CODE REVIEW

**Review by lisagumerman — APPROVED** [review]

File: support/flyway/src/main/java/io/zephyr/support/flyway/ClasspathModuleResourceProvider.java [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+    loadResources();
+  }
+
+  @Override
+  public LoadableResource getResource(String name) {
+    return resources.get(name);
+  }
+
+  @Override
+  public Collection<LoadableResource> getResources(String prefix, String[] suffixes) {
```
Comment (cameronbraid) [inline support/flyway/src/main/java/io/zephyr/support/flyway/ClasspathModuleResourceProvider.java:38]: Should the resources be filtered based on prefix and suffixes ?
